#!/bin/sh
# SMS Custom Actions - replace /etc/forward with this file

SCRIPTSDIR="/etc/sms-actions"

call_scripts() {
# Run asynchronously unless with an extension of ".wait" or ".waitNN" (wait max NN seconds)
D="$SCRIPTSDIR/$1"
shift
scripts=$(ls "$D" | sort)
stop_execution=0 # Initialize the flag to indicate no need to stop the execution
for script in $scripts; do
    [[ -x "$D/$script" ]] || continue
    [[ -f "$D/$script" ]] || continue
    case "$script" in
        *.wait)
            "$D/$script" "$@"
            if [ $? -eq 255 ]; then
              stop_execution=1
            fi
            ;;
        *.wait[0-9]*)
            waitterm=$(echo "$script" | sed -n 's/.*\.wait\([0-9]\+\)$/\1/p')
            waitkill="$((waitterm + 5))" # extra 5 seconds before KILL
            timeout -k $waitkill $waitterm "$D/$script" "$@"
            if [ $? -eq 255 ]; then
              stop_execution=1
            fi
            ;;
        *)
            "$D/$script" "$@" &
            # async scripts are not monitored for execution return code
            ;;
    esac
done
return $stop_execution  # Return the flag status at the end
}

call_scripts "pre" "$@"
if [ $? -eq 1 ]; then
    # Stop execution if any "pre" script set the stop_execution flag
    exit 0
fi

# Call the original script
[[ -x /etc/forward-original ]] && /etc/forward-original "$@" &

call_scripts "post" "$@"
