#!/bin/sh
# SMS Custom Actions - replace /etc/forward with this file

# Call the original script first
[[ -x /etc/forward-original ]] && /etc/forward-original "$@" &

SCRIPTSDIR="/etc/sms-actions"

# Initial scripts in init/ are always executed asynchronously
D="$SCRIPTSDIR/init"
scripts=$(ls "$D" | sort)
for script in $scripts; do
  [[ -f "$D/$script" ]] && [[ -x "$D/$script" ]] && "$D/$script" "$@" &
done

# Normal scripts, ran asynchronously unless they have an extension ".wait" or ".waitNN" (wait max NN seconds)
D="$SCRIPTSDIR"
scripts=$(ls "$D" | sort)
for script in $scripts; do
    [[ -x "$D/$script" ]] || continue
    [[ -f "$D/$script" ]] || continue
    case "$script" in
        *.wait)
            "$D/$script" "$@"
            ;;
        *.wait[0-9]*)
            waitterm=$(echo "$script" | sed -n 's/.*\.wait\([0-9]\+\)$/\1/p')
            waitkill="$((waitterm + 5))" # extra 5 seconds before KILL
            timeout -k $waitkill $waitterm "$D/$script" "$@"
            ;;
        *)
            "$D/$script" "$@" &
            ;;
    esac
done
